version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/node:12

    steps:
      - checkout

      - run:
          name: Deploy to EC2
          command: |
            echo "$smileandhra_pem_file" | base64 --decode > /tmp/private-key.pem
            scp -i /tmp/private-key.pem -r ./* ubuntu@your-ec2-instance-ip:/var/www/smileandhrawebsite
            ssh -i /tmp/private-key.pem ubuntu@your-ec2-instance-ip "cd /var/www/smileandhrawebsite && git pull && sudo systemctl reload nginx"
          environment:
            smileandhra_pem_file: $smileandhra_pem_file

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
