name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH Key
        run: |
            mkdir -p ~/.ssh
            echo "$SMILE_ANDHRA_PEM" > ~/.ssh/smile_andhra_pem.pem
            chmod 600 ~/.ssh/smile_andhra_pem.pem
            ssh-keyscan 43.204.97.217 >> ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
        env:
            SMILE_ANDHRA_PEM: ${{ secrets.SMILE_ANDHRA_PEM }}

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/smile_andhra_pem.pem ubuntu@43.204.97.217 'sudo su && cd /var/www/smileandhrawebsite && git pull && sudo systemctl reload nginx'
        env:
          SMILE_ANDHRA_PEM: ${{ secrets.SMILE_ANDHRA_PEM }}